version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: accounting-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:5000/api
    depends_on:
      - backend
    networks:
      - accounting-network

  backend:
    build: ./backend
    container_name: accounting-backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:Manoj8056%26@postgres:5432/bizsuite
    depends_on:
      - postgres
    networks:
      - accounting-network

  postgres:
    image: postgres:14-alpine
    container_name: accounting-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Manoj8056&
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bizsuite
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - accounting-network

networks:
  accounting-network:
    driver: bridge

volumes:
  postgres-data: